#
# Build stage
#
FROM maven:latest AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml -DskipTests=true clean package

#
# Package stage
#
FROM openjdk:latest
COPY --from=build /home/app/target/sstore-api.jar sstore-api.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","sstore-api.jar"]
