#
# Build stage
#
FROM maven:latest AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml -DskipTests=true package

#
# Package stage
#
FROM openjdk:latest
ADD target/sstore-api.jar sstore-api.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","sstore-api.jar"]
