security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000
src:
  uploads:
    images: "C:/Users/Abdelilah Dehaoui/IdeaProjects/SsToreAPI/src/main/java/com/SsTore/uploads/images"
