security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000
src:
  uploads:
    #imagesDir: C:/uploads/images/
    imagesDir: /uploads/images/
host:
  #ip: http://localhost:8080/images/
  ip: http://35.65.40.24:8080/images/
paypal:
  mode: sandbox
  client:
    id: AQ513-d0usWtBIgd2HRoqsWOiHi8XGPWeeM0eOTrqsHfaZWBNi1FVKBwAmcwh2qp0DiKEol_l0kA1B2Z
    secret: EEDs12PAohpiaDsli76zZ0hnK1oYEvqyj-nXBSlf_LLsN-8KZYoDCKUtF4_JDGx7Hq_HU4ds6m1bE9eK


